# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AR

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'SideMenu'
pod 'SwiftSpinner'
pod 'Fabric', '~> 1.8.2'
pod 'Crashlytics', '~> 3.11.1'
pod 'SwiftLocation', '~> 3.2.3'
pod 'ARCL'
pod 'SwiftExceptionCatcher', :git => 'https://github.com/RedRoma/SwiftExceptionCatcher.git'

end
